# Generated by Django 3.1.4 on 2021-05-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyPost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsinfo',
            name='slug',
            field=models.SlugField(max_length=130, unique=True),
        ),
    ]
