# Generated by Django 3.1.4 on 2021-05-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyPost', '0002_auto_20210529_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandleSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('timeStamp_pass', models.DateTimeField()),
            ],
        ),
    ]
