# Generated by Django 3.1.4 on 2021-05-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyPost', '0004_auto_20210530_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlesignup',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
