# Generated by Django 3.1.4 on 2021-05-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyPost', '0005_handlesignup_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
